version: "3.4"

services:
  mkdocs:
    image: sandipb/mkdocs-material
    ports:
      - "8000:8000"
    volumes:
      - ./:/docs
      - local_cache:/tmp/.local
    depends_on:
      - fix_perms

  deploy:
    image: sandipb/mkdocs-material
    volumes:
      - ./:/docs
      - local_cache:/tmp/.local
      - ${SSH_AUTH_SOCK}:/tmp/agent-sock
    environment:
      - SSH_AUTH_SOCK=/tmp/agent-sock
    # command: gh-deploy
    entrypoint: sh
    depends_on:
      - fix_perms

  fix_perms:
    image: sandipb/mkdocs-material
    volumes:
      - ./:/docs
      - local_cache:/tmp/.local
      - ${SSH_AUTH_SOCK}:/tmp/agent-sock
    user: root
    entrypoint: [ "/bin/sh", "-c" ]
    command: 
      - >
        chown -R mkdocs:mkdocs /tmp &&
        su mkdocs -c "pip install --user -r /docs/requirements_mkdocs.txt"


volumes:
  local_cache:
