version: "3.4"

services:
  mkdocs:
    image: sandipb/mkdocs-material
    ports:
      - "8000:8000"
    volumes:
      - ./:/docs
      - local_cache:/home/mkdocs/.local
    depends_on:
      - fix_perms

  deploy:
    image: sandipb/mkdocs-material
    volumes:
      - ./:/docs
      - local_cache:/home/mkdocs/.local
    command: gh-deploy
    depends_on:
      - fix_perms

  fix_perms:
    image: sandipb/mkdocs-material
    volumes:
      - ./:/docs
      - local_cache:/home/mkdocs/.local
    user: root
    entrypoint: [ "/bin/sh", "-c" ]
    command: 
      - >
        chown -R mkdocs /home/mkdocs/.local &&
        su mkdocs -c "pip install --user -r /docs/requirements_mkdocs.txt"


volumes:
  local_cache:
