site_name: "sandipb.net : references"
site_url: https://sandipb.github.io
site_description: "Collection of reference docs"
site_author: Sandip Bhattacharya

repo_name: sandipb/sandipb.github.io
repo_url: https://github.com/sandipb/sandipb.github.io

copyright: Copyright &copy; 2021 Sandip Bhattacharya. All content under CC-BY.

nav:
  - Home: index.md
  - Cloud:
      - Containers: cloud-native/containers.md
      - Kubernetes: cloud-native/kubernetes.md
      - Gcloud Runbook: cloud-native/gcloud.md
  - Distributed Systems: distributed_systems.md
  - Performance: performance.md
  - Git: git.md
  - Operating Systems:
      - Linux/Ubuntu: operating-systems/linux_ubuntu.md
  - Programming:
      - Golang: programming/golang.md
  - Observability:
      - Prometheus: observability/prometheus.md
  - Blog 🔗: "https://blog.sandipb.net"


theme:
  name: material
  logo: resources/favicon-96x96.png
  favicon: resources/favicon-96x96.png
  custom_dir: docs/resources/custom_theme
  # palette:
  #   primary: Teal
  #   accent: Indigo
  features:
    - tabs
    - toc.integrate
extra:
  repo_icon: github
  analytics:
    provider: custom
    property: ref.sandipb.net 



extra_css:
  - resources/stylesheets/extra.css

markdown_extensions:
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - docs/resources/custom_theme/.icons
  - attr_list
